GET http://localhost:3000/api/landscapes

###

GET http://localhost:3000/api/landscapes/0.8750757516956194

###

POST http://localhost:3000/api/landscapes
Content-Type: application/json

{
    "name": "Hund",
    "flower": "Gullviva",
    "animal": "Hasselmus",
}

###

PUT http://localhost:3000/api/landscapes/0.34060266470033906
Content-Type: application/json

{
    "name": "hello",
    "flower": "tja",
    "animal": "tjo",
    "id":
}

###

DELETE http://localhost:3000/api/landscapes/0.9162667707977143
Content-Type: application/json

 {
    "name": "Dalarna",
    "flower": "Ängsklocka",
    "animal": "Berguv",
    "id": 0.9162667707977143
  }
