GET http://localhost:3000/api/landscapes

###

POST http://localhost:3000/api/landscapes
Content-Type: application/json

{
    "name": "Hund",
    "flower": "Gullviva",
    "animal": "Hasselmus"
    
    
}

###

PUT http://localhost:3000/api/landscapes/4
Content-Type: application/json

{
    "name": "Handske",
    "flower": "Gullviva",
    "animal": "Hasselmus",
    "id": 4 
}

###

DELETE http://localhost:3000/api/landscapes/4
Content-Type: application/json

{
    "name": "Handske",
    "flower": "Gullviva",
    "animal": "Hasselmus",
    "id": 4 
}